// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220324171343_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GroupSize")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Email = "test@test.com",
                            GroupName = "Farquad Squad",
                            GroupSize = 4,
                            Phone = "801-123-1234"
                        });
                });

            modelBuilder.Entity("Mission12.Models.TimeSlot", b =>
                {
                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentDateTime");

                    b.HasIndex("AppointmentId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            AppointmentId = 1
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 5, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 6, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentDateTime = new DateTime(2022, 4, 9, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Mission12.Models.TimeSlot", b =>
                {
                    b.HasOne("Mission12.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
